runtime: nodejs22
env: standard
instance_class: F1

automatic_scaling:
  min_instances: 1
  max_instances: 1

env_variables:
  NODE_ENV: "production"
  PORT: "8080"
  JWT_SECRET: "10093cfcc73657f9a073807be56b70111d66cfbbe0d0323ec9bd22931a1bd41f"
  DATABASE_URL: "34.105.70.60"
  DATABASE_USERNAME: "admin"
  DATABASE_PASSWORD: "password123"
  DATABASE_DB: "gitdb"
  DATABASE_PORT: "5432"
  REDIS_HOST: "34.105.70.60"
  REDIS_PORT: "6379"

entrypoint: node index.js
